swagger: '2.0'
info:
  description: Swagger Spec for the Nuapay TPP OpenBanking/PSD2. Provides AISP, PISP
    and Banks Endpoints
  version: '1.0'
  title: Nuapay TPP API Specification
  contact:
    name: Nuapay
    email: 'api.support@nuapay.com'
  license:
    name: 'Nuapay'
    url: 'https://sentenial.com'
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://www.nuapay.com/wp-content/uploads/2018/04/nuapay.svg'
host: 'api.nuapay.com'
basePath: /tpp
tags:
  - name: AISP Service
    description: |-
      Account access endpoints allow a merchant to,
      - Request access to a users account details
      - Retrieve an existing account access request
      - Delete an existing account access request
      - Get a list of account details 
      - Get the balance of a specific user account
      - Get the transaction history of a specific user account

      Note: Before querying GET accounts, balances or transactions you must first generate an account access request.
  - name: Bank Service
    description: |-
      Bank endpoints allow a merchant to,
      - Retrieve a list of banks that support the Open Banking scheme
      - View details of a specific bank that supports the Open Banking scheme
  - name: PISP Service
    description: |-
      Payment initiation endpoints allow a merchant to,
      - Initiate payment requests in Open Banking
      - Retrieve the status of a previously initiated payment request
      - Reverse a previously initiated payment request 
paths:
  /account-requests:
    post:
      tags:
        - AISP Service
      summary: Create Account Access
      description: Create an account access request
      operationId: createAccountRequestUsingPOST
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
        - OriginatorApiKey: []
  /account-requests/{accountRequestReference}:
    get:
      tags:
        - AISP Service
      summary: Retrieve Account Access
      description: Get an account request
      operationId: getAccountRequestUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
        - OriginatorApiKey: []
    delete:
      tags:
        - AISP Service
      summary: Delete Account Access
      description: Delete an account request
      operationId: deleteAccountRequestUsingDELETE
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
        - OriginatorApiKey: []
  /accounts:
    get:
      tags:
        - AISP Service
      summary: Retrieve Account(s)
      description: Get a list of accounts
      operationId: getAccountsUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
        - OriginatorApiKey: []
  /accounts/{accountId}/balances:
    get:
      tags:
        - AISP Service
      summary: Retrieve Account Balance
      description: Get Balances related to an account
      operationId: getAccountBalancesUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
        - OriginatorApiKey: []
  /accounts/{accountId}/transactions:
    get:
      tags:
        - AISP Service
      summary: Retrieve Account Transactions
      description: Get transactions related to an account
      operationId: getAccountTransactionsUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
        - OriginatorApiKey: []
  /banks:
    get:
      tags:
        - Bank Service
      summary: Retrieve Banks
      description: Get Supported Banks On This TPP
      operationId: getBanksUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
          - openbanking_pisp
        - OriginatorApiKey: []
  /banks/{bankId}:
    get:
      tags:
        - Bank Service
      summary: View Bank
      description: View Bank Details
      operationId: getBankUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_aisp
          - openbanking_pisp
        - OriginatorApiKey: []
  /payments:
    post:
      tags:
        - PISP Service
      summary: Create Payment
      description: Create a payment request POST endpoint
      operationId: createPaymentUsingPOST
      security:
        - OriginatorOAuth2:
          - openbanking_pisp
        - OriginatorApiKey: []
  /payments/{paymentId}:
    get:
      tags:
        - PISP Service
      summary: Retrieve Payment
      description: GET Payment details endpoint
      operationId: getUsingGET
      security:
        - OriginatorOAuth2:
          - openbanking_pisp
        - OriginatorApiKey: []
  /payments/{paymentId}/reverse:
    post:
      tags:
        - PISP Service
      summary: Reverse a Payment POST endpoint
      description: Reverse a Payment POST endpoint
      operationId: reversePaymentUsingPOST
      security:
        - OriginatorOAuth2:
          - openbanking_pisp
        - OriginatorApiKey: []
securityDefinitions:
  OriginatorApiKey:
    type: basic
  OriginatorOAuth2:
    type: oauth2
    tokenUrl: https://api.nuapay.com/oauth/token_key
    flow: password
    scopes:
      openbanking_aisp: Account Information Service Provider access.
      openbanking_pisp: Payment Initiation Service Provider access.